=== LatentDragonInDeep/redisorm/src/latentdragon/redisorm/redisorm-configure.dtd
<!DOCTYPE configuration PUBLIC "-//redisorm.org//DTD Config 3.0//EN" "http://redisorm.org/dtd/redisorm-configure.dtd">


        <!ELEMENT redisorm-configuration (session-factory)>

<!ELEMENT session-factory (properties+,mappings*)>
<!ELEMENT properties (property+)>
<!ELEMENT mappings (mapping-xml*,mapping-annotation*)>

<!ELEMENT property (#PCDATA)>
<!ATTLIST property name CDATA
        ("host"|"port"|"username"|"passowrd"|
        "pool_size"|"timeout"|"fetch_size"|"batch-size"|
        "useUnicode"|"characterEncoding"|"autoCommit"|"deamonize"|
        "logLevel"|"logFile"|"databaseNum"|"compression"|
        "dbfilename"|"maxClients"|"maxMemory"|"vm-enable"|
        "activerehashing")
        (#REQUIRED)>

<!ELEMENT mapping-xml EMPTY>
<!ATTLIST mapping-xml resource CDATA #REQUIRED>

<!ELEMENT mapping-annotation EMPTY>
<!ATTLIST mapping-annotation class CDATA #REQUIRED>

=== LatentDragonInDeep/redisorm/src/redisorm.cfg.xml
<?xml version='1.0' encoding='utf-8'?>
<!--<!DOCTYPE redisorm-configuration SYSTEM "http://redisorm.org/dtd/redisorm-configure.dtd">-->
<redisorm-configuration>
    <session-factory>
        <properties>
            <!--设置数据库的连接url-->
            <property name="host">localhost</property>
            <!--设置数据库的端口号-->
            <property name="port">6379</property>
            <!--连接数据库的用户名-->
            <property name="username">root</property>
            <!--连接数据库是密码-->
            <property name="password">iShare2018</property>
            <!--数据库连接池的大小-->
            <property name="pool_size">20</property>
            <!--超时时间-->
            <property name="timeout">1000</property>
        </properties>
        <mappings>
            <mapping-xml resource="TestXML.rbm.xml"/>
            <mapping-annotation class="TestAnnotation"/>
        </mappings>
    </session-factory>
</redisorm-configuration>
